import AppLayout from '../components/AppLayout';

export default function Terms() {
  return (
    <AppLayout>
      <div className="page-content">
        <div className="term-banner">
          <span className="banner-prompt">$</span> ./terms --read
          <span className="banner-status">● LEGAL</span>
        </div>

        <h1 className="docs-h1">TERMS OF SERVICE</h1>
        <p className="docs-lead">
          THESE TERMS GOVERN YOUR USE OF SIGNUPDOGGY ("THE SERVICE"). BY ACCESSING
          OR USING THE SERVICE YOU AGREE TO BE BOUND BY THEM. IF YOU DO NOT AGREE,
          DO NOT USE THE SERVICE.
        </p>
        <p className="docs-p" style={{ opacity: 0.7 }}>
          LAST UPDATED: 2026
        </p>

        <h2 className="docs-h2"># 1. ACCEPTANCE</h2>
        <p className="docs-p">
          BY CREATING AN ACCOUNT, GENERATING AN API KEY, OR SUBMITTING A REQUEST
          TO THE SIGNUPDOGGY API, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND
          AGREE TO THESE TERMS. IF YOU ARE ACCEPTING ON BEHALF OF AN ORGANIZATION,
          YOU REPRESENT THAT YOU HAVE AUTHORITY TO BIND THAT ORGANIZATION.
        </p>

        <h2 className="docs-h2"># 2. SERVICE DESCRIPTION</h2>
        <p className="docs-p">
          SIGNUPDOGGY IS A FRAUD-PREVENTION API. THE SERVICE EVALUATES EMAIL
          ADDRESSES, IP ADDRESSES, AND PHONE NUMBERS PROVIDED BY YOU IN YOUR
          SIGNUP TRAFFIC AND RETURNS RISK SCORES, SIGNALS (DISPOSABLE EMAIL, VPN,
          PROXY, TOR, VIRTUAL PHONE), AND A RECOMMENDATION (ALLOW / REVIEW / BLOCK).
        </p>
        <p className="docs-p">
          THE SERVICE IS PROVIDED "AS IS" AND IS INTENDED TO ASSIST — NOT REPLACE —
          YOUR OWN FRAUD-DETECTION PROCESSES. YOU REMAIN SOLELY RESPONSIBLE FOR
          DECISIONS YOU MAKE BASED ON THE SERVICE'S OUTPUT.
        </p>

        <h2 className="docs-h2"># 3. ACCOUNTS & ELIGIBILITY</h2>
        <p className="docs-p">
          YOU MUST PROVIDE A VALID EMAIL ADDRESS AND A SECURE PASSWORD TO CREATE
          AN ACCOUNT. YOU ARE RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF
          YOUR CREDENTIALS AND YOUR API KEYS. YOU MUST BE AT LEAST 16 YEARS OLD
          (OR THE AGE OF DIGITAL CONSENT IN YOUR JURISDICTION, WHICHEVER IS
          HIGHER) TO USE THE SERVICE.
        </p>

        <h2 className="docs-h2"># 4. API KEYS & ACCEPTABLE USE</h2>
        <p className="docs-p">
          API KEYS ARE PERSONAL TO YOUR ACCOUNT. DO NOT SHARE, RESELL, OR
          DISTRIBUTE YOUR KEYS. YOU MUST NOT:
        </p>
        <ul className="docs-p" style={{ paddingLeft: '1.5em', listStyle: 'none' }}>
          <li>▸ USE THE SERVICE TO VIOLATE ANY APPLICABLE LAW OR REGULATION</li>
          <li>▸ SUBMIT PERSONAL DATA OF THIRD PARTIES WITHOUT A LAWFUL BASIS UNDER GDPR, CCPA, OR EQUIVALENT PRIVACY LAW</li>
          <li>▸ ATTEMPT TO REVERSE-ENGINEER, SCRAPE, OR MASS-DOWNLOAD OUR DETECTION DATABASES</li>
          <li>▸ RESELL OR SUBLICENSE THE SERVICE OR ITS OUTPUT IN COMPETITION WITH SIGNUPDOGGY</li>
          <li>▸ INTERFERE WITH OR DISRUPT THE INTEGRITY OR PERFORMANCE OF THE SERVICE</li>
          <li>▸ USE THE SERVICE TO STALK, HARASS, OR HARM ANY INDIVIDUAL</li>
        </ul>

        <h2 className="docs-h2"># 5. FEES & PAYMENT</h2>
        <p className="docs-p">
          SIGNUPDOGGY IS A PAY-AS-YOU-GO SERVICE. EVERY API CALL COSTS $0.01
          DEDUCTED FROM YOUR PRE-PAID CREDIT BALANCE, PROCESSED BY DODO
          PAYMENTS. CREDITS NEVER EXPIRE. NO MONTHLY FEE, NO SUBSCRIPTION, NO
          SALES CALL. ALL FEES ARE NON-REFUNDABLE EXCEPT WHERE REQUIRED BY LAW.
        </p>
        <p className="docs-p">
          WE MAY CHANGE PRICING WITH 30 DAYS' NOTICE. CONTINUED USE AFTER THE
          EFFECTIVE DATE OF A PRICE CHANGE CONSTITUTES ACCEPTANCE OF THE NEW
          PRICING.
        </p>

        <h2 className="docs-h2"># 6. INTELLECTUAL PROPERTY</h2>
        <p className="docs-p">
          THE SERVICE, INCLUDING ITS DETECTION DATABASES, ALGORITHMS, BRANDING,
          AND SOURCE CODE, IS OWNED BY SIGNUPDOGGY AND PROTECTED BY INTELLECTUAL
          PROPERTY LAW. THESE TERMS GRANT YOU A LIMITED, NON-EXCLUSIVE,
          NON-TRANSFERABLE LICENSE TO USE THE SERVICE VIA THE PUBLIC API ONLY.
          YOU RETAIN ALL RIGHTS TO DATA YOU SUBMIT TO THE API.
        </p>

        <h2 className="docs-h2"># 7. TERMINATION</h2>
        <p className="docs-p">
          YOU MAY CLOSE YOUR ACCOUNT AT ANY TIME FROM THE DASHBOARD. WE MAY
          SUSPEND OR TERMINATE YOUR ACCESS IF YOU BREACH THESE TERMS, ABUSE THE
          SERVICE, OR IF WE ARE REQUIRED TO DO SO BY LAW. UPON TERMINATION, YOUR
          RIGHT TO USE THE SERVICE CEASES IMMEDIATELY.
        </p>

        <h2 className="docs-h2"># 8. DISCLAIMERS & LIABILITY</h2>
        <p className="docs-p">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED "AS IS"
          AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
          INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR
          A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE
          SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT EVERY FRAUDULENT
          SIGNUP WILL BE DETECTED.
        </p>
        <p className="docs-p">
          IN NO EVENT SHALL SIGNUPDOGGY'S TOTAL LIABILITY FOR ALL CLAIMS ARISING
          OUT OF OR RELATING TO THE SERVICE EXCEED THE GREATER OF (A) THE FEES
          YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) USD $100. WE
          SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          OR PUNITIVE DAMAGES.
        </p>

        <h2 className="docs-h2"># 9. GOVERNING LAW</h2>
        <p className="docs-p">
          THESE TERMS ARE GOVERNED BY THE LAWS OF INDIA, WITHOUT REGARD TO ITS
          CONFLICT-OF-LAW RULES. ANY DISPUTE ARISING FROM THESE TERMS SHALL BE
          SUBJECT TO THE EXCLUSIVE JURISDICTION OF THE COURTS IN KERALA, INDIA.
        </p>

        <h2 className="docs-h2"># 10. CHANGES & CONTACT</h2>
        <p className="docs-p">
          WE MAY UPDATE THESE TERMS FROM TIME TO TIME. MATERIAL CHANGES WILL BE
          ANNOUNCED BY EMAIL AND IN-APP NOTICE AT LEAST 14 DAYS BEFORE THEY TAKE
          EFFECT. THE "LAST UPDATED" DATE AT THE TOP OF THIS PAGE REFLECTS THE
          CURRENT VERSION.
        </p>
        <p className="docs-p">
          QUESTIONS ABOUT THESE TERMS? EMAIL{' '}
          <a href="mailto:legal@signupdoggy.dev" style={{ color: 'var(--accent)' }}>
            legal@signupdoggy.dev
          </a>
          .
        </p>
      </div>
    </AppLayout>
  );
}
