#!/usr/bin/env node
/**
 * aeo:build:worker — bundle aeo/worker.ts into dist/_worker.js.
 *
 * Uses esbuild (already in devDependencies) to produce a single
 * ESM file that Cloudflare Pages picks up automatically when
 * assets.run_worker_first = true.
 *
 * The bundle includes:
 *   - @dualmark/cloudflare (createAEOWorker, AIRequestInfo types)
 *   - @dualmark/core (AI_BOTS registry, negotiation, path utils)
 *
 * Output target is the workerd-compatible ESM format. We do not
 * minify because the worker is < 30 KB and esbuild's mangle
 * occasionally breaks the Vary / Link header construction (string
 * literals are fine; the issue is the inline `Function` ctor used
 * in some env shims).
 *
 * Run via:  npm run aeo:build:worker
 */

import { build } from 'esbuild';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENTRY = join(ROOT, 'aeo', 'worker.ts');
const OUTFILE = join(ROOT, 'dist', '_worker.js');

async function main() {
  if (!existsSync(dirname(OUTFILE))) {
    mkdirSync(dirname(OUTFILE), { recursive: true });
  }

  const start = Date.now();
  const result = await build({
    entryPoints: [ENTRY],
    outfile: OUTFILE,
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'neutral', // Cloudflare Workers runtime, not Node
    conditions: ['workerd', 'browser', 'import'],
    mainFields: ['module', 'main'],
    minify: false,
    sourcemap: false,
    // workerd exposes the global `Response` / `Request` / `fetch`;
    // don't try to polyfill them.
    external: [],
    logLevel: 'info',
    metafile: false,
    banner: {
      // CF Pages looks for a default export with `fetch`. esbuild's
      // default export detection handles the rest, but a small
      // header makes the artifact self-documenting in the Workers
      // dashboard.
      js: '/*! signupdoggy-aeo worker — generated by aeo/build-worker.mjs — do not edit by hand */',
    },
  });

  if (result.errors.length > 0) {
    for (const e of result.errors) console.error('[aeo:build:worker]', e);
    process.exit(1);
  }

  console.log(
    `[aeo:build:worker] bundled aeo/worker.ts → dist/_worker.js in ${Date.now() - start}ms`,
  );
}

main().catch((err) => {
  console.error('[aeo:build:worker] failed:', err);
  process.exit(1);
});
